triggers:
- description: null
  envs: []
  last_enabled_at: 2024-12-20 10:06:16.206585
  name: Real-time predictions
  pipeline_uuid: predict
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-12-20 10:05:00
  status: active
  token: 857ea51208ad4e2ca57aa9e54f8b36d9
  variables: {}
