triggers:
- description: null
  envs: []
  last_enabled_at: 2024-12-20 09:25:36.799435
  name: Retrain model hourly
  pipeline_uuid: automatic_retraining
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    allow_blocks_to_fail: true
    create_initial_pipeline_run: true
    skip_if_previous_running: true
  sla: null
  start_time: 2024-12-20 00:00:00
  status: active
  token: f5d2ab976e8d441aaf9a2870bacf39fb
  variables: {}
